name: "Commit Changes"
description: "Commit changes and set the changes_detected output to true if changes are present, otherwise set the changes_detected output to false."

inputs:
  message:
    description: "The commit message"
    required: true
    type: string

outputs:
  changes_detected:
    description: "Whether changes were detected and committed"
    value: ${{ steps.commit_changes.outputs.changes_detected }}

runs:
  using: composite
  steps:
    - name: Commit changes
      id: commit_changes
      env:
        MESSAGE: ${{ inputs.message }}
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "$MESSAGE"
          echo "changes_detected=true" >> "$GITHUB_OUTPUT"
        else
          echo "No changes detected."
          echo "changes_detected=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
