name: "Publish npm package"
description: "Builds and publishes an npm package"

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm install
      shell: bash
    
    - name: Build package
      run: npm run build
      shell: bash

    - name: Publish to npm
      run: npm publish --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}


inputs:
  NPM_AUTH_TOKEN:
    description: "NPM token to allow publishing"
    required: true
