name: "CI"
description: "Verify code with linting and testing"

runs:
  using: composite
  steps:
  - name: Use Node.js
    uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
    with:
      node-version: 22
      cache: 'npm'

  - name: Use latest NPM version
    run: npm install -g npm@latest
    shell: bash
    
  - name: Install dependencies
    run: npm ci
    shell: bash

  - name: Build package
    run: npm run build --if-present
    shell: bash

  - name: Fetch from main
    run: git fetch --unshallow origin main
    shell: bash

  - name: Check version number
    run: |
      npx alex-c-line check-lockfile-version-discrepancy
      npx alex-c-line check-version-number-change
    shell: bash

  - name: Run linting checks
    run: npm run lint
    shell: bash

  - name: Run tests
    if: ${{ inputs.run-tests == 'true' }}
    run: npm test
    shell: bash

inputs:
  run-tests:
    description: "Include testing"
    required: false
    default: true
    type: boolean
