name: "Update peer dependencies"
description: "Update peer dependencies in an NPM project, change the minor version, and creates a pull request with updates"

runs:
  using: composite
  steps:
  - name: Use Node.js
    uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
    with:
      node-version: 22
      cache: "npm"
  - name: Setup GitHub user
    run: |
      git config --global user.name "AlexUpBot"
      git config --global user.email "alexupbot@bot.com"
    shell: bash

  - name: Check if pull request to update peer dependencies already exists
    run: |
      PULL_REQUEST_ID=$(gh pr list --state open --head alex-up-bot/update-peer-dependencies --json number --jq '.[].number')
      if [ -n "$PULL_REQUEST_ID" ]; then
        echo "Dependency update pull request already exists (#$PULL_REQUEST_ID). Exiting."
        exit 1
      fi
    env:
      GH_TOKEN: ${{ inputs.PAT_GITHUB }}
    shell: bash
  
  - name: Use latest NPM version
    run: npm install -g npm@latest
    shell: bash

  - name: Install dependencies
    run: npm ci
    shell: bash

  - name: Change version number
    run: npm version minor -m "Change version number to v%s"
    shell: bash

  - name: Update Node dependencies
    run: npm run update-peer-dependencies || true
    shell: bash


  - name: Create Pull Request
    uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
    with:
      token: ${{ inputs.PAT_GITHUB }}
      branch: alex-up-bot/update-peer-dependencies
      base: main
      commit-message: Update peer dependencies
      title: "Update peer dependencies"

inputs:
  PAT_GITHUB:
    description: "GitHub token to allow pull request to be created"
    required: true
