name: "Publish npm package"
description: "Builds and publishes an npm package"

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/
    
    - name: Use latest NPM version
      run: npm install -g npm@latest
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
    
    - name: Build package
      run: npm run build
      shell: bash

    - name: Publish to npm
      run: npm publish --access public
      shell: bash
